"""
!!! DO NOT EDIT THIS FILE !!! - create config_local.py, copy relevant variables, and change them there instead.
"""

RETRY_PAUSE = 2  # in seconds
RETRY_COUNT = 30
ENTITIES_TAKE_MAX = 1000

MOYSKLAD_TOKEN = 'very_secret_token'
FILENAME_BASE_XLS_OUTPUT = 'bundles'


# Import local overrides
try:
    from config_local import *
except ImportError or ModuleNotFoundError:
    pass
